# Generated by Django 5.1 on 2024-08-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.JSONField(default=dict, help_text="in JSON format")),
            ],
            options={
                "verbose_name_plural": "App Setting",
            },
        ),
    ]
